services:
    wordpress:
        build: .
        ports:
            - "8080:80"
        environment:
            DB_NAME: wordpress
            DB_USER: wordpress
            DB_PASSWORD: wordpress
            DB_HOST: mysql
        depends_on:
            - mysql
        volumes:
            - wp_data:/var/www/wordpress
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: wordpress
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress
        restart: always
        volumes:
            - db_data:/var/lib/mysql
volumes:
    db_data:
    wp_data: